rpcp2p: rpcp2p_decentralized.cc
	g++ -std=c++11 rpcp2p_decentralized.cc -lrpc -lpthread -o server
	cp server ./peer1/
	mv ./peer1/server ./peer1/peer1
	cp server ./peer2/
	mv ./peer2/server ./peer2/peer2
	cp server ./peer3/
	mv ./peer3/server ./peer3/peer3
	cp server ./peer4/
	mv ./peer4/server ./peer4/peer4
	cp server ./peer5/
	mv ./peer5/server ./peer5/peer5
	cp server ./peer6/
	mv ./peer6/server ./peer6/peer6
	cp server ./peer7/
	mv ./peer7/server ./peer7/peer7
	cp server ./peer8/
	mv ./peer8/server ./peer8/peer8
	cp server ./server1/
	mv ./server1/server ./server1/server1
	cp server ./server2/
	mv ./server2/server ./server2/server2
	cp server ./server3/
	mv ./server3/server ./server3/server3
	cp server ./server4/
	mv ./server4/server ./server4/server4
	cp server ./server5/
	mv ./server5/server ./server5/server5
	cp server ./server6/
	mv ./server6/server ./server6/server6
	cp server ./server7/
	mv ./server7/server ./server7/server7
	cp server ./server8/
	mv ./server8/server ./server8/server8
	cp config ./peer1/
	cp config ./peer2/
	cp config ./peer3/
	cp config ./peer4/
	cp config ./peer5/
	cp config ./peer6/
	cp config ./peer7/
	cp config ./peer8/
	rm server

.PHONY: clean

clean: ./peer1/peer1 ./peer2/peer2 ./peer3/peer3 ./peer4/peer4 ./peer5/peer5 ./peer6/peer6 ./peer7/peer7 ./peer8/peer8 ./server1/server1 ./server2/server2 ./server3/server3 ./server4/server4 ./server5/server5 ./server6/server6 ./server7/server7 ./server8/server8
	
	rm ./peer1/peer1
	rm ./peer2/peer2
	rm ./peer3/peer3
	rm ./peer4/peer4
	rm ./peer5/peer5
	rm ./peer6/peer6
	rm ./peer7/peer7
	rm ./peer8/peer8
	rm ./server1/server1
	rm ./server2/server2
	rm ./server3/server3
	rm ./server4/server4
	rm ./server5/server5
	rm ./server6/server6
	rm ./server7/server7
	rm ./server8/server8
	rm ./peer1/config
	rm ./peer2/config
	rm ./peer3/config
	rm ./peer4/config
	rm ./peer5/config
	rm ./peer6/config
	rm ./peer7/config
	rm ./peer8/config
